# Site settings
title: flickr photoset test
email: tamouse.lists@gmail.com
description: a quick test of the flickr_photoset plugin
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
markdown: kramdown
exclude: [README.md, flickr_authtest.rb]

flickr:
  api_key: <%= ENV['b56f423a00a1fdad94eb5acf8405876e'] || '' %>
  shared_secret: <%= ENV['071cf51443eeabe7'] || '' %>
  access_token: <%= ENV['72157680511989826-677dd85808bb21c4'] || '' %>
  access_secret: <%= ENV['8e72f68de9251448'] || '' %>
  
